import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-content-secondary relative min-h-screen overflow-hidden`}
                style={{
                    minHeight: "100vh",
                }}
            >
                {/* Atmospheric Radial Gradient Background */}
                <div
                    aria-hidden="true"
                    className="pointer-events-none fixed inset-0 -z-10"
                    style={{
                        background:
                            "radial-gradient(ellipse at 50% 0%, #0D0C14 0%, #191429 100%)",
                        width: "100vw",
                        height: "100vh",
                    }}
                />
                {/* Glowing Arc at Bottom */}
                <div
                    aria-hidden="true"
                    className="pointer-events-none fixed left-1/2 -translate-x-1/2 bottom-[-120px] -z-10"
                    style={{
                        width: "120vw",
                        height: "320px",
                        background:
                            "linear-gradient(90deg, transparent 0%, rgba(217,70,239,0.3) 50%, transparent 100%)",
                        filter: "blur(100px)",
                        borderRadius: "50% 50% 100% 100% / 0% 0% 100% 100%",
                    }}
                />
                {children}
            </body>
        </html>
    );
}
